### ISSUE TITLE
can we remove port 19092 from KAFKA_LISTENERS for node2

### ISSUE THREAD

**Issue by moglideveloper** [izzyacademy/kafka-in-a-box#2]
Thanks for closing https://github.com/izzyacademy/kafka-in-a-box/issues/1.

But port 19092 is still  defined in KAFKA_LISTENERS

 @https://github.com/izzyacademy/kafka-in-a-box/blob/f5c07541dcbb528256b58f77d8a219fd25ef4b07/compose/kraft/multi-node-docker-compose.yml#L62
#
Kindly confirm, if that can also be removed.

If it there for some specific reason, please help me to understand the reason for keeping it (I am not a Kafka expert 😃) 

---

Also, what is the best channel to reach you out, if I have any configuration related doubts related to https://github.com/izzyacademy/kafka-in-a-box

**Comment by izzyacademy** [comment]
Yes, you can remove that controller port since the node is a broker and not a controller or combined node.

Regarding how to reach me, you can create issues here in the github repo for now and I will be setting up a community in discord soon and will share the link as soon as that is setup.

I also plan to post another update for the Kafka 3.1 release so these settings will be updated soon.

In the 3.1 release [KAFKA-13456](https://issues.apache.org/jira/browse/KAFKA-13456) is enforcing these settings are correct so it will be easier to catch these type of config errors going forward.

https://issues.apache.org/jira/browse/KAFKA-13456

I will be publishing another docker image to docker hub soon for the 3.1.0 release using the official release artifacts.

Thanks for reporting the issue.
